name: run

on: 
  push:
     branches:
             -main
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
             - uses: actions/checkout@v2
             - uses: actions/setup-python@v2
               with:
                   python-versions: 3.0
             - run:
                python print2.py
              
      
